server:
  port: 8050
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/crm-billing-service
    username: postgres
    password: asdasd123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.turkcell.billingservice: DEBUG
    org.hibernate.SQL: DEBUG