version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: billing-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crm-billing-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdasd123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 